import React from 'react'

export const metadata = {
    title: "about us",
    description: "Generated by create next app",
    keywords: "dshop,ecommerce,",
  };

const layout = ({children}) => {
  return (
    
    <div>
        <h1>about layout</h1>
        {children}</div>
  )
}

export default layout