import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";


export const metadata = {
  title: "D-SHOP",
  description: "Generated by create next app",
  keywords: "dshop,ecommerce,",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <header className="dark:bg-zinc-900 py-3 w-full">
          <div className="container mx-auto flex justify-between items-center">
          <h1 className="font-extrabold text-2xl">LOGO</h1>
          <Navbar/>
          </div>



          </header>
        {children}
      </body>
    </html>
  );
}
